[sentient-2026]
reviewer = Deann B.
date = May 17, 2026
text = Maxim made me a cover that is truly artwork. During my book launch, I have had so many people tell me they loved the cover and I have no doubt it is a large part of my book's success. Working with him was the easiest part of my self publishing process, he understood the assignment from the very beginning and it took less than a week to have a finished cover that looked exactly like what I saw in my mind. Can't recommend him enough!

[arcusian-2026]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[moonstone-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[pallomand-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[solton-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[prizraki-2026]
; placeholder for future review

[red-planet-2-2026]
; placeholder for future review

[damned-2026]
; placeholder for future review
