[sentient-2026]
reviewer = Deann B.
date = May 17, 2026
text = Maxim made me a cover that is truly artwork. During my book launch, I have had so many people tell me they loved the cover and I have no doubt it is a large part of my book's success. Working with him was the easiest part of my self publishing process, he understood the assignment from the very beginning and it took less than a week to have a finished cover that looked exactly like what I saw in my mind. Can't recommend him enough!

[arcusian-2026]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[moonstone-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[pallomand-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[solton-2025]
reviewer = James M.
date = Nov 14, 2025
text = I've used Max for two book covers. He's a talented artist who provides attention to detail and cover-design expertise. Max worked diligently with me to create the exact illustration I was looking for, often providing unique insight to the design process. I highly recommend him.

[metal-flesh-2025]
reviewer = Edward S.
date = Nov 10, 2025
text = Fantastic in all departments

[trek-2025]
reviewer = Darren R.
date = Mar 16, 2025
text = Maxim did a fantastic job for me on two covers for the first two books of a series I am working on. In one case he designed a full cover- the back looked as good as the front, and only the ebook cover for the other. Both turned out great – with, what I think, the perfect tone for the subject matter. And the perfect font. The details he included and the depth of field was amazing. His turnaround time was also very fast. I plan on using him again for my next book.

[pandoras-daugher]
reviewer = David H.
date = Mar 9, 2026
text = Very professional, very responsive. Delivered high quality product on time. Made requested changes immediately.

[superunknown]
reviewer = Socrates J.
date = Apr 14, 2026
text = Working with Maxim as a cover designer was a highly professional experience from start to finish. Communication was clear, consistent, and timely throughout the entire process, which made collaboration straightforward and efficient. He demonstrated a strong understanding of the project requirements and executed them. He delivering a final product that mostly aligned with my vision, although I could have communicated my needs better. Turnaround times were prompt without sacrificing quality, and he remained responsive to feedback, making adjustments where needed. Overall, a reliable and skilled collaborator. I would confidently recommend his services to anyone looking for quality design work delivered with professionalism and efficiency.

[shards-of-humanity]
reviewer = Dale B.
date = Jan 1, 2026
text = I'm incredibly grateful to have worked with Maxim. He's talented, patient, and communicates throughout the process. He works with your schedule, offers great advice, and ultimately brings to life exactly what you want. I needed a custom cover of a specific scene within my book as well as two diagrams, and Maxim went above and beyond. I will absolutely use him for the second book. Thanks again Maxim!

[the-sideways-8]
reviewer = Mark R.
date = Dec 23, 2024
text = Maxim is a true professional. He responded promptly, perfectly captured my vision, and delivered outstanding work—for the third time! He's incredibly easy to work with. I gave him a long list of ideas, and he completely nailed it. Highly recommend. Thanks for your creative design, Maxim.

[first-contact]
reviewer = Albert Z.
date = Jul 17, 2024
text = Maxim was great to work with, created concepts very fast and was always very responsive to feedback. I love the aesthetic and the painted quality of his images.

[ashes-of-the-wake]
reviewer = Jonas V.
date = Sep 7, 2024
text = Max was excellent! Such a wonderful dark tone and great ideas. It was a pleasure working with him and I could not be happier!

[prizraki-2026]
; placeholder for future review

[red-planet-2-2026]
; placeholder for future review

[damned-2026]
; placeholder for future review
